apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
spec:
  selector:
    matchLabels:
      app: be
  replicas: 3
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
        - name: be
          image: be
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: be-service
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: be
  type: NodePort
