version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: DockerfileBackend
    container_name: backend
    ports:
      - "4000:4000"
    networks:
      - my-network
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network: